language: android
android:
  components:
    - build-tools-20.0.0
    - $ANDROID_TARGET
    - sys-img-armeabi-v7a-$ANDROID_TARGET
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
    
script: ./gradlew assembleRelease

before_install:
  - pwd
  - ls -la
  - chmod +x /.gradlew
