language: android
android:
  components:
    - build-tools-27.0.3
    - $ANDROID_TARGET
    - sys-img-armeabi-v7a-$ANDROID_TARGET
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
    
script:
  - gradle clean build
  #./gradlew assembleRelease
  
before_install:
  #- pwd
  #- ls -la
  #- chmod +x ./gradlew

before_script:
    #- wget http://services.gradle.org/distributions/gradle-2.2-all.zip
    #- unzip gradle-2.2-all.zip
    #- export GRADLE_HOME=$PWD/gradle-2.2
    #- export PATH=$GRADLE_HOME/bin:$PATH
